Repository gordon-cs/gordon-360-ui, pull requests merged in 2019-04, with the labels that each got.

#405 Fix phone number from '927' to '867'
  src/components/OfficeList/index.js
Labels: bug

#409 Display meal plan info for SuperAdmins in addition to students.
  src/views/Home/components/DiningBalance/index.js
Labels: Minor UI change

#410 Add hall search
  src/services/goStalk.js
  src/views/PeopleSearch/index.js
Labels: Feature
