Repository gordon-cs/gordon-360-ui, pull requests merged in 2021-07, with the labels that each got.

#1190 Update Phone Number Dialog
  package-lock.json
  package.json
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.js
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.scss
  src/components/Profile/components/PersonalInfoList/index.js
  src/services/user.js
Labels: 3 Points, Feature

#1244 Prettier Gordon Dialog Box
  src/components/GordonDialogBox/index.js
  src/components/GordonDialogBox/index.scss
  src/components/Header/components/PeopleSearch/index.js
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.js
  src/components/QuickLinksDialog/index.js
Labels: 2 Points, Code Quality, Visual Design

#1257 RELEASE: UI Adjustments to Home and Advanced People Search
  package-lock.json
  src/components/Error/index.js
  src/components/GordonDialogBox/index.js
  src/components/GordonDialogBox/index.scss
  src/components/GordonUnauthorized/index.js
  src/components/Header/components/PeopleSearch/index.js
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.js
  src/components/QuickLinksDialog/index.js
  src/setupProxy.js
  src/views/Events/index.js
  src/views/Help/index.js
  src/views/Home/components/CLWCreditsDaysLeft/index.js
  src/views/Home/components/Carousel/index.js
  src/views/Home/components/GuestWelcome/index.js
  src/views/InvolvementProfile/components/ContactList/index.js
  src/views/InvolvementProfile/components/ContactListItem/index.js
  src/views/InvolvementProfile/components/Membership/components/AdminCard/index.js
  src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.js
  src/views/InvolvementProfile/components/Membership/components/MemberList/index.js
  src/views/InvolvementProfile/components/Membership/components/NonMemberButtons/index.js
  src/views/InvolvementProfile/index.js
  src/views/InvolvementsAll/index.js
  src/views/News/index.js
  src/views/PeopleSearch/components/PeopleSearchResult/index.js
  src/views/PeopleSearch/index.js
  src/views/WellnessCheck/index.js
Labels: Release

#1291 S21 Academic Check-In Final
  package-lock.json
  src/components/Header/components/NavButtonsRightCorner/index.js
  src/routes.js
  src/services/checkIn.js
  src/services/user.js
  src/setupProxy.js
  src/views/AcademicCheckIn/components/AcademicCheckInWelcome/index.js
  src/views/AcademicCheckIn/components/CompletedCheckIn/index.js
  src/views/AcademicCheckIn/components/ConfirmCheckIn/index.js
  src/views/AcademicCheckIn/components/EmergencyContactUpdate/index.js
  src/views/AcademicCheckIn/components/PrivacyAgreement/index.js
  src/views/AcademicCheckIn/components/PrivacyAgreement/privacy.json
  src/views/AcademicCheckIn/components/RaceEthnicity/index.js
  src/views/AcademicCheckIn/components/UpdatePhone/index.js
  src/views/AcademicCheckIn/index.js
  src/views/AcademicCheckIn/index.scss
  src/views/Home/index.js
  src/views/InvolvementProfile/components/ContactListItem/index.js
Labels: Feature
