Repository gordon-cs/gordon-360-ui, pull requests merged in 2021-02, with the labels that each got.

#956 Apartapp functional components
  src/components/AlertDialogBox/index.js
  src/services/housing.js
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/components/SaveButton/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/ApartmentApp/index.js
Labels: ApartApps, Code Quality

#968 Add documentation to the README for manual deploy
  README.md
Labels: Documentation

#954 ApartApp refactoring, consistent terminology for application editor
  .expo/packager-info.json
  .expo/settings.json
  .github/workflows/ci.yml
  .travis.yml
  GUIDES.md
  README.md
  public/web.config
  scripts/deploy.sh
  src/components/AlertDialogBox/index.js
  src/components/ApartAppSaveButton/index.js
  src/components/ApartmentApplicantList/components/ApplicantListItem/index.js
  src/components/ApartmentApplicantList/index.js
  src/components/ApartmentHallSelection/components/HallListItem/index.js
  src/components/ApartmentHallSelection/index.js
  src/services/housing.js
  src/services/user.js
  src/setupProxy.js
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/ApartmentApp/index.js
  src/views/Timesheets/components/ShiftItem/index.js
  src/views/Timesheets/index.js
  web_config
Labels: ApartApps

#1012 Merged from develop and other requested improvements
  README.md
  src/setupProxy.js
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/PeopleSearch/index.js
Labels: ApartApps, Code Quality

#1013 Moved custom alert dialog features to existing dialog box component
  src/components/AlertDialogBox/index.js
  src/components/GordonDialogBox/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: 1 Point, ApartApps, Code Quality

#963 ApartApp Get Application ID
  src/services/housing.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: 1 Point, ApartApps, ApartApps MVP
