Repository gordon-cs/gordon-360-ui, pull requests merged in 2021-06, with the labels that each got.

#1191 Changed some codes to make NOTES only appear on My Profile page
  src/components/Profile/components/PersonalInfoList/index.js
Labels: Bug

#1208 S21 Final Update: Advanced People Search Checkboxes
  src/services/goStalk.js
  src/views/PeopleSearch/index.js
Labels: 2 Points, Feature, Profile Page

#1213 People Search Larger Images Toggle
  src/views/PeopleSearch/components/PeopleSearchResult/index.js
  src/views/PeopleSearch/components/PeopleSearchResult/peopleSearchResult.scss
  src/views/PeopleSearch/index.js
Labels: 1 Point, Search, Visual Design
