Repository gordon-cs/gordon-360-ui, pull requests merged in 2021-04, with the labels that each got.

#1061 Apartapp Debug MVP features
  .env.development
  package-lock.json
  src/services/housing.js
  src/setupProxy.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/components/ApplicantSubTable/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/index.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApartmentHeader/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicationDataTable/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/ApartmentApp/index.js
Labels: ApartApps, ApartApps MVP

#1062 ApartApp User Agreements
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: 3 Points, ApartApps, ApartApps MVP

#1066 Removed points calculation and added handling of 404 not found
  src/services/housing.js
Labels: ApartApps, ApartApps MVP

#1063 ApartApp code quality improvements
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationTableHead/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: 3 Points, ApartApps, Code Quality

#1067 ApartApps Fix application load bug and other changes from review
  src/services/housing.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps

#1070 Apartapp simplified CSV generation and refresh data button
  src/views/ApartmentApp/components/StaffMenu/index.js
Labels: ApartApps, ApartApps MVP, Code Quality

#926 Apartapp develop
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/sw_global_variables.js
  src/_vars.scss
  src/components/GordonDialogBox/index.js
  src/components/Header/components/PeopleSearch/index.js
  src/components/Header/components/PeopleSearch/people-search.scss
  src/routes.js
  src/services/error.js
  src/services/housing.js
  src/setupProxy.js
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/applicationTable.scss
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/components/ApplicantSubTable/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/components/HallSubTable/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationTableHead/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/index.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApartmentHeader/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicationDataTable/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
  src/views/ApartmentApp/components/StudentApplication/components/SaveButton/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/ApartmentApp/index.js
  src/views/News/index.js.orig
Labels: ApartApps, ApartApps MVP

#1071 Fixed ApartApp page loading
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/index.js
Labels: ApartApps, ApartApps MVP

#1074 ApartApp - More user-friendly date display
  src/services/housing.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicationDataTable/index.js
  src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
Labels: ApartApps

#1031 Apartapp develop off campus
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/components/OffCampusListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/Login/gordon-logo-vertical-white.svg
Labels: ApartApps

#1080 Replace white background pictures with transparent bg
  public/images/android-icon-144x144.png
  public/images/android-icon-192x192.png
  public/images/android-icon-36x36.png
  public/images/android-icon-48x48.png
  public/images/android-icon-72x72.png
  public/images/android-icon-96x96.png
  public/images/apple-icon-114x114.png
  public/images/apple-icon-120x120.png
  public/images/apple-icon-144x144.png
  public/images/apple-icon-152x152.png
  public/images/apple-icon-180x180.png
  public/images/apple-icon-57x57.png
  public/images/apple-icon-60x60.png
  public/images/apple-icon-72x72.png
  public/images/apple-icon-76x76.png
  public/images/apple-icon-precomposed.png
  public/images/apple-icon.png
  public/images/favicon-16x16.png
  public/images/favicon-32x32.png
  public/images/favicon-96x96.png
  public/images/ms-icon-144x144.png
  public/images/ms-icon-150x150.png
  public/images/ms-icon-310x310.png
  public/images/ms-icon-70x70.png
Labels: Good First Issue

#1077 ApartApp - Bug fix for date submitted saying "Invalid DateTime"
  src/views/ApartmentApp/components/StudentApplication/components/ApplicationDataTable/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/components/OffCampusListItem/index.js
Labels: ApartApps, Bug

#1075 ApartApp - UI Style Tweaks
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/components/ApplicantSubTable/index.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApartmentHeader/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/components/SaveButton/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/components/OffCampusListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/ApartmentApp/index.js
Labels: 3 Points, ApartApps

#1072 Apartapp - Change over to combined ApplicationDetails obj in state
  src/services/housing.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationTableHead/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/index.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicationDataTable/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/components/OffCampusListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps

#1082 Apartapp develop - April 15
  src/services/housing.js
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/components/ApplicantSubTable/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationTableHead/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/index.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApartmentHeader/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicationDataTable/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/components/SaveButton/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/components/HallListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/components/OffCampusListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/ApartmentApp/index.js
  src/views/Login/gordon-logo-vertical-white.svg
Labels: ApartApps MVP

#1087 ApartApp - Left justify application instructions
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps

#1089 ApartApp - Submit application feature
  src/services/housing.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps, ApartApps MVP

#1090 ApartApp - Urgent bug fixes
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps, ApartApps MVP, Bug

#1091 1084 ApartApp (1) Change application page title (in top left) from "Apartment App" to the more formal "Apartment Application"
  src/routes.js
Labels: ApartApps, ApartApps MVP

#1095 ApartApp - Update/filter applicant data during first load from API
  src/services/housing.js
  src/services/user.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps

#1096 Added the createSnackbar helper function
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps
