Repository gordon-cs/gordon-360-ui, pull requests merged in 2021-05, with the labels that each got.

#1094 Apartapp fix isApplicantValid
  src/services/housing.js
  src/services/user.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps

#1097 Fixed the editor state not updating after changing the editor
  src/services/housing.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/ApartmentApp/index.js
Labels: ApartApps

#1100 Apartapp cleanup
  src/services/housing.js
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/components/SaveButton/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/ApartmentApp/index.js
Labels: ApartApps, Code Quality

#1106 Update submit button to disable when application is already submitted
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps, ApartApps MVP

#1093 Apartapp develop
  package-lock.json
  package.json
  src/components/DynamicButton/index.js
  src/routes.js
  src/services/housing.js
  src/services/user.js
  src/views/ApartmentApp/apartmentApp.scss
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/index.js
  src/views/ApartmentApp/components/StaffMenu/index.js
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/components/SaveButton/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallSelection/index.js
  src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusSection/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
  src/views/ApartmentApp/index.js
Labels: ApartApps

#1103 Fix script for npm start
  package-lock.json
  package.json
Labels: Bug, Dependencies

#1099 Update and refactor About page design
  package-lock.json
  src/views/About/about.scss
  src/views/About/contributors.json
  src/views/About/index.js
Labels: Code Quality, Enhancement, Modification

#1111 Refactor and Update Content on Help Page
  src/views/Help/help.scss
  src/views/Help/index.js
Labels: Enhancement

#1107 ApartApp - Improve user feedback when changing editor
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps, Code Quality

#1120 Add 2019-20 Software Development Team
  src/views/About/contributors.json
Labels: Page Content

#1108 Apartapp - Update and refactor callback functions and more
  src/components/GordonDialogBox/index.js
  src/services/housing.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/components/ApplicantSubTable/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/components/HallSubTable/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationTableHead/index.js
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/index.js
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallChoiceList/components/HallChoiceListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/HallChoiceList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/InstructionsCard/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusList/components/OffCampusListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusList/index.js
  src/views/ApartmentApp/components/StudentApplication/index.js
Labels: ApartApps, Code Quality, Enhancement, Modification

#1109 ApartApp - Exclude [object] from CSV
  src/views/ApartmentApp/components/StaffMenu/index.js
Labels: ApartApps
