Repository gordon-cs/gordon-360-ui, pull requests merged in 2022-11, with the labels that each got.

#1557 [Rec-IM] Activity data fetching from/posting to the API
  .env.development
  src/services/recim.ts
  src/views/RecIM/components/CreateActivityForm/index.js
  src/views/RecIM/components/List/Listing/index.js
  src/views/RecIM/components/List/index.js
  src/views/RecIM/views/Home/index.js
Labels: Rec-IM

#1570 Add Agreement Checkbox for Winter Housing Hosting
  src/views/ApartmentApp/components/StudentApplication/components/Agreements/index.js
Labels: ApartApps

#1533 Remove ID Numbers from Membership, Request, and Admin Routes
  .env.development
  .gitignore
  src/components/Profile/components/MembershipsList/index.js
  src/services/admin.ts
  src/services/membership.ts
  src/services/request.ts
  src/services/session.ts
  src/services/utils.ts
  src/views/Admin/components/AdminList/components/AdminListItem/index.js
  src/views/Admin/components/AdminList/index.js
  src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsReceived/index.js
  src/views/InvolvementProfile/components/Membership/components/AdminCard/index.js
  src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.js
  src/views/InvolvementProfile/components/Membership/components/NonMemberButtons/index.js
  src/views/InvolvementProfile/components/Membership/index.js
  src/views/InvolvementProfile/index.js
  src/views/InvolvementsAll/components/Requests/components/RequestSent/index.js
  src/views/InvolvementsAll/components/Requests/components/RequestsReceived/index.js
Labels: Code Quality, Privacy, Epic

#1573 Patch: Fix styling of memberships list
  src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.js
Labels: Bug

#1569 Patch: GordonDialogBox Content Padding
  src/components/GordonDialogBox/GordonDialogBox.module.scss
Labels: Bug

#1578 Remove admin list and point users to groups site
  src/views/Admin/Admin.module.scss
  src/views/Admin/components/AdminList/components/AdminListItem/index.js
  src/views/Admin/components/AdminList/index.js
  src/views/Admin/index.js
Labels: Bug

#1579 Dependency Bump - moment, minimist, terser, loader-utils, minimatch, recursive-readdir
  package-lock.json
  package.json
Labels: Dependencies

#1575 [Rec-IM] UI Service Routes
  src/services/http.ts
  src/services/recim.ts
  src/services/recim/activity.ts
  src/services/recim/match.ts
  src/services/recim/participant.ts
  src/services/recim/recim.ts
  src/services/recim/series.ts
  src/services/recim/sport.ts
  src/services/recim/team.ts
  src/views/RecIM/components/Forms/CreateActivityForm/index.js
  src/views/RecIM/components/Forms/CreateTeamForm/index.js
  src/views/RecIM/views/Home/index.js
Labels: Rec-IM
