Repository gordon-cs/gordon-360-ui, pull requests merged in 2022-09, with the labels that each got.

#1504 Add new font url & update default styling
  .env
  .env.development
  .env.production
  src/app.global.scss
  src/views/Home/components/CLWCreditsDaysLeft/CLWCreditsDaysLeft.module.scss
  src/views/Home/components/DiningBalance/DiningBalance.module.scss
Labels: Bug

#1505 Release: Resolve Gotham Font Errors
  .env
  .env.development
  .env.production
  src/app.global.scss
  src/views/Home/components/CLWCreditsDaysLeft/CLWCreditsDaysLeft.module.scss
  src/views/Home/components/DiningBalance/DiningBalance.module.scss
Labels: Release

#1506 Clifton strengths csv upload
  package-lock.json
  package.json
  src/components/SpreadsheetUploader/SpreadsheetUploader.module.scss
  src/components/SpreadsheetUploader/index.js
  src/services/cliftonStrengths.ts
  src/theme.js
  src/views/Admin/components/CliftonStrengthsUpload/CliftonStrengthsUpload.module.scss
  src/views/Admin/components/CliftonStrengthsUpload/cliftonStrengthsUploadTemplate.csv
  src/views/Admin/components/CliftonStrengthsUpload/index.js
  src/views/Admin/index.js
Labels: Feature

#1514 HotFix: Fix PeopleSearch ClassType
  src/services/goStalk.ts
Labels: Bug

#1524 Fix dining balance days left chart
  src/views/Home/components/DiningBalance/index.js
Labels: Bug

#1525 Refactor people search
  package-lock.json
  package.json
  src/components/GordonOffline/index.js
  src/components/GordonUnauthorized/index.js
  src/components/Header/components/QuickSearch/PeopleSearch.module.scss
  src/components/Header/components/QuickSearch/index.js
  src/components/Header/index.js
  src/components/Profile/components/Identification/index.js
  src/components/Profile/components/OfficeInfoList/OfficeInfoList.module.scss
  src/components/Profile/components/OfficeInfoList/index.js
  src/components/Profile/components/PersonalInfoList/index.js
  src/hooks/useAuthGroups.ts
  src/index.js
  src/services/housing.ts
  src/services/peopleSearch.ts
  src/services/quickSearch.ts
  src/services/user.ts
  src/services/utils.ts
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/components/ApplicationRow/components/ApplicantSubTable/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/components/ApplicantListItem/index.js
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.js
  src/views/ApartmentApp/components/StudentApplication/components/OffCampusList/index.js
  src/views/PeopleSearch/PeopleSearch.module.scss
  src/views/PeopleSearch/components/PeopleSearchResult/PeopleSearchResult.module.scss
  src/views/PeopleSearch/components/PeopleSearchResult/index.js
  src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
  src/views/PeopleSearch/components/SearchFieldList/components/SearchField/SearchField.module.scss
  src/views/PeopleSearch/components/SearchFieldList/components/SearchField/index.tsx
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
  src/views/PeopleSearch/index.js
  src/views/PeopleSearch/index.tsx
Labels: Code Quality, Search
