Repository gordon-cs/gordon-360-ui, pull requests merged in 2023-10, with the labels that each got.

#2121 Add Alert Message for Unsigned Rec/IM Waiver
  src/theme.ts
  src/views/RecIM/views/Home/Home.module.scss
  src/views/RecIM/views/Home/index.jsx
Labels: Rec-IM

#2125 Refactor schedule: simplify data flow, streamline calendar and dialog, use typescript, remove `moment`.
  package-lock.json
  package.json
  src/app.global.scss
  src/components/Profile/components/SchedulePanel/ScheduleHeader.module.scss
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.jsx
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.tsx
  src/components/Profile/components/SchedulePanel/components/ScheduleDialog/ScheduleDialog.module.scss
  src/components/Profile/components/SchedulePanel/components/ScheduleDialog/index.jsx
  src/components/Profile/components/SchedulePanel/components/ScheduleDialog/index.tsx
  src/components/Profile/components/SchedulePanel/index.jsx
  src/components/Profile/components/SchedulePanel/index.tsx
  src/services/schedule.ts
  src/services/session.ts
Labels: Dependencies, Code Quality

#2124 Quick Search: Use MUI Autocomplete, refactor
  package-lock.json
  package.json
  src/components/Header/components/QuickSearch/QuickSearch.module.scss
  src/components/Header/components/QuickSearch/index.jsx
  src/components/Header/components/QuickSearch/index.tsx
  src/services/quickSearch.ts
  src/views/ApartmentApp/components/StudentApplication/components/ApplicantList/index.jsx
  src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx
  src/views/RecIM/components/RecIMQuickSearch/RecIMQuickSearch.module.scss
  src/views/RecIM/components/RecIMQuickSearch/index.jsx
Labels: Dependencies, Code Quality

#2128 Remove unused pages and dependencies
  package-lock.json
  package.json
  src/components/AppRedirect/index.jsx
  src/components/SymptomsDialog/SymptomsDialog.module.scss
  src/components/SymptomsDialog/index.jsx
  src/components/WellnessQuestion/WellnessQuestion.module.scss
  src/components/WellnessQuestion/index.jsx
  src/routes.jsx
  src/services/jobs.ts
  src/services/wellness.ts
  src/views/Events/index.jsx
  src/views/Home/index.jsx
  src/views/Timesheets/Timesheets.module.scss
  src/views/Timesheets/components/SavedShiftsList/SavedShiftsList.module.scss
  src/views/Timesheets/components/SavedShiftsList/index.jsx
  src/views/Timesheets/components/ShiftDisplay/ShiftDisplay.module.scss
  src/views/Timesheets/components/ShiftDisplay/index.jsx
  src/views/Timesheets/components/ShiftItem/ShiftItem.module.scss
  src/views/Timesheets/components/ShiftItem/index.jsx
  src/views/Timesheets/index.jsx
  src/views/WellnessCheck/components/HealthStatus/HealthStatus.module.scss
  src/views/WellnessCheck/components/HealthStatus/index.jsx
  src/views/WellnessCheck/index.jsx
Labels: Dependencies, Code Quality

#2130 Fix jotform waiver url
  src/views/RecIM/components/Forms/WaiverForm/index.jsx
  src/views/RecIM/views/Home/index.jsx
Labels: Bug

#2131 Hotfix: jotform waiver url
  src/views/RecIM/components/Forms/WaiverForm/index.jsx
Labels: Bug
