Repository gordon-cs/gordon-360-ui, pull requests merged in 2023-05, with the labels that each got.

#1774 Add a Mailto link in the search results page
  src/views/PeopleSearch/components/PeopleSearchResult/PeopleSearchResult.module.scss
  src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
Labels: Good First Issue, Search

#1792 Fix erroneous redirects
  src/components/AppRedirect/index.jsx
  src/services/auth.ts
  src/services/checkIn.ts
Labels: Bug

#1799 Use ReactGA properly
  src/views/Home/components/GuestWelcome/index.jsx
Labels: Broken Feature

#1800 Hotfix: Update imports for `react-ga4` to fix broken guest view
  src/views/Home/components/GuestWelcome/index.jsx
Labels: Broken Feature

#1809 Implemented enter key submission in GordonDialogBox
  src/components/GordonDialogBox/index.jsx
Labels: Rec-IM

#1780 [Rec-IM] Create & Edit custom participant in Admin page
  src/services/recim/participant.ts
  src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx
  src/views/RecIM/components/Forms/ParticipantForm/index.jsx
  src/views/RecIM/components/List/Listing/index.jsx
  src/views/RecIM/components/List/index.jsx
  src/views/RecIM/components/QuickSearch/QuickSearch.module.scss
  src/views/RecIM/components/QuickSearch/index.jsx
  src/views/RecIM/views/Admin/index.jsx
Labels: Rec-IM
