Repository gordon-cs/gordon-360-ui, pull requests merged in 2023-07, with the labels that each got.

#1910 clean up deprecated styles packages
  src/components/GordonTooltip/GordonTooltip.module.scss
  src/components/GordonTooltip/index.jsx
  src/components/Header/components/NavAvatarRightCorner/NavAvatarRightCorner.module.scss
  src/components/Header/components/NavAvatarRightCorner/index.jsx
  src/components/PWAInstructions/PWAInstructions.module.scss
  src/components/PWAInstructions/index.jsx
  src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsReceived/RequestsReceived.module.scss
  src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsReceived/index.jsx
  src/views/Timesheets/Timesheets.module.scss
  src/views/Timesheets/components/ShiftItem/ShiftItem.module.scss
  src/views/Timesheets/components/ShiftItem/index.jsx
  src/views/Timesheets/index.jsx
Labels: 3 Points, S23

#1886 Mailbox instructions link
  src/components/Profile/components/PersonalInfoList/PersonalInfoList.module.scss
  src/components/Profile/components/PersonalInfoList/index.jsx
Labels: 1 Point, S23

#1895 Create ThemePaletteDocs.md
  docs/ThemePaletteDocs.md
Labels: Documentation, Color/Style

#1968 turned the patch request to change the membership privacy to put
  src/services/membership.ts
Labels: S23

#1971 turned both routes from patch to put
  src/components/Profile/components/OfficeInfoList/UpdateOfficeLocationDialog/index.jsx
  src/services/user.ts
Labels: S23

#1944 arranging drop down of departments in people search
  src/services/peopleSearch.ts
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: 1 Point, S23

#1844 Implement people search by graduation year
  src/services/peopleSearch.ts
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: 3 Points, S23

#1870 Term selector after conversion
  src/components/Profile/components/SchedulePanel/ScheduleHeader.module.scss
  src/components/Profile/components/SchedulePanel/components/EditDescriptionDialog/index.jsx
  src/components/Profile/components/SchedulePanel/components/RemoveScheduleDialog/index.jsx
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.jsx
  src/components/Profile/components/SchedulePanel/components/myScheduleDialog/index.jsx
  src/components/Profile/components/SchedulePanel/index.jsx
  src/services/myschedule.ts
  src/services/schedule.ts
  src/services/schedulecontrol.ts
Labels: 3 Points, S23

#1942 Alumni checkbox will only be set checked by default if the user is only an alumni
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: S23

#1805 Fix Google Analytics Tracking Code
  .env.production
Labels: Bug

#1982 added shaded note about involvements privacy
  src/components/Profile/components/MembershipsList/index.jsx
Labels: 1 Point, S23

#1935 S23/add UI version to about page
  package.json
  save-ui-version.sh
  src/services/version.ts
  src/views/About/index.jsx
  src/views/About/version.json
Labels: 2 Points, S23

#2001 S23 change office hours route
  src/components/Profile/components/OfficeInfoList/OfficeInfoList.module.scss
  src/components/Profile/components/OfficeInfoList/index.jsx
  src/components/Profile/components/SchedulePanel/ScheduleHeader.module.scss
  src/components/Profile/components/SchedulePanel/components/EditDescriptionDialog/index.jsx
  src/components/Profile/components/SchedulePanel/index.jsx
  src/components/Profile/index.jsx
Labels: Modification, 2 Points, S23

#1990 People search results after back button
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: Search, 2 Points, S23

#2018 Updated Loader with New Image
  index.css
  index.html
  public/images/360-centered-yellow.png
  public/images/360-centered.png
  public/images/by_students_for_students.png
Labels: S23, Color/Style

#1960 S23 add to calendar for schedule panel
  src/components/Profile/components/SchedulePanel/ScheduleHeader.module.scss
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.jsx
  src/components/Profile/components/SchedulePanel/components/ScheduleDialog/ScheduleDialog.module.scss
  src/components/Profile/components/SchedulePanel/components/ScheduleDialog/index.jsx
  src/components/Profile/components/SchedulePanel/index.jsx
  src/services/schedule.ts
Labels: Feature, schedule, S23

#2009 Move Office Hours and Edit Office Hours button to the Office Info Card
  src/components/Profile/components/OfficeInfoList/EditDescriptionDialog/EditDescriptionDialog.module.scss
  src/components/Profile/components/OfficeInfoList/EditDescriptionDialog/index.jsx
  src/components/Profile/components/OfficeInfoList/index.jsx
  src/components/Profile/components/SchedulePanel/index.jsx
Labels: Modification, Profile Page, 2 Points, S23

#2004 Color Mode Switching and Listening Logic + Appearance Settings Dialog
  src/app.jsx
  src/components/Header/components/NavButtonsRightCorner/index.jsx
  src/components/Nav/components/NavLinks/index.jsx
  src/components/PaletteSwitcherDialog/index.tsx
  src/components/ThemeModeSwitcher/index.jsx
  src/components/ThemeModeSwitcher/modeSwitcher.module.scss
  src/hooks/index.js
  src/hooks/useWatchSystemColorScheme.ts
  src/theme.ts
Labels: Feature, Color/Style

#1993 base for the editing mail stop on profile
  src/components/Profile/components/OfficeInfoList/UpdateMailDestinationDialog/index.jsx
  src/components/Profile/components/OfficeInfoList/index.jsx
  src/services/user.ts
Labels: 3 Points, S23

#2040 consistency in style and code in Change Office Hours
  src/components/Profile/components/OfficeInfoList/EditDescriptionDialog/EditDescriptionDialog.module.scss
  src/components/Profile/components/OfficeInfoList/EditDescriptionDialog/index.jsx
  src/components/Profile/components/OfficeInfoList/UpdateOfficeHoursDialog/index.jsx
  src/components/Profile/components/OfficeInfoList/index.jsx
Labels: 1 Point, S23

#2037 schedule dialog improvement
  src/components/Profile/components/SchedulePanel/components/ScheduleDialog/index.jsx
  src/components/Profile/components/SchedulePanel/index.jsx
  src/services/schedule.ts
Labels: schedule, S23

#2048 Scss changes for note design
  src/components/Profile/components/MembershipsList/MembershipsList.module.scss
  src/components/Profile/components/MembershipsList/index.jsx
Labels: S23

#2014 Update Calendar options and label
  src/components/EventList/components/EventItem/index.jsx
Labels: 1 Point, S23

#2055 [Rec-IM] switching match tabs duplicates
  src/views/RecIM/components/Forms/WaiverForm/index.jsx
  src/views/RecIM/components/List/index.jsx
  src/views/RecIM/views/Home/index.jsx
Labels: Bug, Rec-IM, S23

#2049 Quick fix for timesheet shift tooltip colors
  src/views/Timesheets/components/ShiftItem/ShiftItem.module.scss
Labels: Color/Style

#2060 [Rec-IM] auto sched parameters
  src/services/recim/series.ts
  src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
Labels: Rec-IM, S23

#1831 S23 allow various prefix for links (new commit on develop as base instead of recim)
  src/components/Profile/components/Identification/components/SocialMediaLinks/components/LinksDialog/index.jsx
  src/services/socialMedia.tsx
Labels: 1 Point

#2074 S23 reload card office info update
  src/components/Profile/components/OfficeInfoList/UpdateMailDestinationDialog/index.jsx
  src/components/Profile/components/OfficeInfoList/UpdateOfficeHoursDialog/index.jsx
  src/components/Profile/components/OfficeInfoList/index.jsx
Labels: Bug, S23

#2069 clearing when toggle switches
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: Bug, S23

#2078 Add-to-Calendar minor improvements
  src/components/EventList/components/EventItem/index.jsx
  src/components/Profile/components/SchedulePanel/ScheduleHeader.module.scss
  src/components/Profile/components/SchedulePanel/components/ScheduleDialog/index.jsx
  src/components/Profile/components/SchedulePanel/index.jsx
Labels: 1 Point, schedule, S23

#2087 corrected slider sensitivity
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: Bug, S23

#2042 [Rec-IM] participant statuses
  src/services/auth.ts
  src/views/RecIM/components/List/Listing/index.jsx
  src/views/RecIM/components/List/index.jsx
  src/views/RecIM/views/Admin/index.jsx
Labels: Rec-IM, S23

#2075 [Rec-IM] match page update
  src/views/RecIM/components/List/Listing/Listing.module.scss
  src/views/RecIM/components/List/Listing/index.jsx
  src/views/RecIM/components/List/index.jsx
  src/views/RecIM/views/Match/index.jsx
Labels: Rec-IM, S23

#2088 [Rec-IM] Ladder Match Page
  src/views/RecIM/components/List/Listing/Listing.module.scss
  src/views/RecIM/components/List/Listing/index.jsx
  src/views/RecIM/components/List/index.jsx
  src/views/RecIM/views/Match/index.jsx
Labels: Rec-IM, S23

#2036 [Rec-IM] Update admin permissions
  src/services/auth.ts
  src/views/RecIM/components/List/Listing/Listing.module.scss
  src/views/RecIM/components/List/Listing/index.jsx
  src/views/RecIM/components/List/index.jsx
  src/views/RecIM/views/Admin/index.jsx
Labels: Rec-IM, S23

#2035 Recim Dark Mode Conversion Work
  src/theme.ts
  src/views/RecIM/components/RecIMBracket/RecIMBracket.module.scss
  src/views/RecIM/components/RecIMQuickSearch/RecIMQuickSearch.module.scss
  src/views/RecIM/views/Admin/Admin.module.scss
  src/views/RecIM/views/Match/Match.module.scss
  src/views/RecIM/views/Team/Team.module.scss
Labels: Color/Style

#2092 S23/recim fix invites
  src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx
  src/views/RecIM/components/List/Listing/index.jsx
  src/views/RecIM/components/List/index.jsx
  src/views/RecIM/views/Team/index.jsx
Labels: Bug, Rec-IM, S23

#2085 Header and Navigation Overhaul
  public/images/gc_2pi_yellow_logo_56_vert.png
  public/images/gc_360_yellow_logo_56_no_text.png
  public/images/gc_360_yellow_logo_56_vert.png
  src/components/Header/Header.module.scss
  src/components/Header/components/NavButtonsRightCorner/NavButtonsRightCorner.module.scss
  src/components/Header/components/NavButtonsRightCorner/index.jsx
  src/components/Header/index.jsx
  src/components/Nav/Nav.module.scss
  src/components/Nav/components/NavLinks/NavLinks.module.scss
  src/components/Nav/index.jsx
  src/project-name.js
Labels: Modification, 2 Points

#1945 started implementing the design for planned graduation year on profile
  src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/UpdatePlannedGradYear.module.scss
  src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/index.jsx
  src/components/Profile/components/PersonalInfoList/index.jsx
  src/services/user.ts
  src/views/CoCurricularTranscript/guestTranscript.tsx
Labels: 3 Points, S23

#2046 Meal Plan link Form
  src/views/Home/components/DiningBalance/index.jsx
Labels: 1 Point, S23

#2098 S23 show schedule taken as both faulty or student
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.jsx
  src/components/Profile/components/SchedulePanel/index.jsx
  src/services/schedule.ts
Labels: 1 Point

#2102 Implement full name into current participant get
  src/views/RecIM/components/List/Listing/index.jsx
Labels: Rec-IM

#2105 [Rec-IM] Halls/Affiliation management
  src/services/recim/affiliations.ts
  src/services/recim/match.ts
  src/services/recim/series.ts
  src/services/recim/team.ts
  src/views/RecIM/components/Forms/EditMatchStatsForm/EditMatchStatsForm.module.scss
  src/views/RecIM/components/Forms/EditMatchStatsForm/index.jsx
  src/views/RecIM/components/Forms/Form/index.jsx
  src/views/RecIM/components/Forms/Forms.module.scss
  src/views/RecIM/components/Forms/SeriesForm/index.jsx
  src/views/RecIM/components/Forms/SeriesPlacementForm/index.jsx
  src/views/RecIM/components/Forms/TeamForm/index.jsx
  src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
  src/views/RecIM/views/Activity/index.jsx
  src/views/RecIM/views/Home/Home.module.scss
  src/views/RecIM/views/Home/components/AffiliationsChart/index.jsx
  src/views/RecIM/views/Home/index.jsx
  src/views/RecIM/views/Team/index.jsx
Labels: Rec-IM

#2106 [Rec-IM] Auto Schedule Estimate
  src/components/GordonDialogBox/GordonDialogBox.module.scss
  src/services/recim/series.ts
  src/views/RecIM/views/Activity/components/ScheduleList/index.jsx
  src/views/RecIM/views/Home/Home.module.scss
  src/views/RecIM/views/Home/index.jsx
Labels: Feature, Rec-IM
