Repository gordon-cs/gordon-360-ui, pull requests merged in 2023-06, with the labels that each got.

#1802 Add instructions to use ssh when cloning repository.
  docs/Developer's Guide.md
Labels: Documentation

#1791 Update packages
  package-lock.json
  package.json
  src/components/AppRedirect/index.jsx
  src/components/GordonLimitedAvailability/index.jsx
  src/components/Profile/components/Identification/index.jsx
  src/views/ApartmentApp/index.jsx
  src/views/BannerSubmission/components/NewBannerDialog/index.jsx
  src/views/Events/index.jsx
  src/views/IDUploader/index.jsx
  src/views/InvolvementProfile/index.jsx
  src/views/News/index.jsx
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: Dependencies

#1795 Refactor ID Uploader to Function Component... + Misc. Fixes
  src/components/GordonDialogBox/GordonDialogBox.module.scss
  src/components/GordonDialogBox/index.jsx
  src/components/GordonDialogBox/index.tsx
  src/components/GordonLimitedAvailability/index.jsx
  src/components/GordonLimitedAvailability/index.tsx
  src/components/GordonUnauthenticated/index.tsx
  src/components/GordonUnauthorized/index.jsx
  src/components/Header/index.jsx
  src/components/Nav/components/NavLinks/index.jsx
  src/components/PhotoCropper/PhotoCropper.module.scss
  src/components/PhotoCropper/index.tsx
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.jsx
  src/components/QuickLinksDialog/components/LinksList/images/GordonFavicon.ico
  src/components/QuickLinksDialog/components/LinksList/index.jsx
  src/components/QuickLinksDialog/images/Canvas.ico
  src/components/QuickLinksDialog/images/GoGordonFavicon.ico
  src/components/QuickLinksDialog/images/MyGordonFavicon.ico
  src/components/QuickLinksDialog/images/favicon.ico
  src/components/QuickLinksDialog/index.jsx
  src/components/QuickLinksDialog/index.tsx
  src/contexts/UserContext.tsx
  src/hooks/useWindowSize.ts
  src/services/logging.ts
  src/views/Admin/index.jsx
  src/views/ApartmentApp/index.jsx
  src/views/BannerSubmission/index.jsx
  src/views/CoCurricularTranscript/index.tsx
  src/views/EnrollmentCheckIn/index.jsx
  src/views/EventsAttended/index.jsx
  src/views/IDUploader/IDUploader.module.scss
  src/views/IDUploader/image.png
  src/views/IDUploader/index.jsx
  src/views/MyProfile/index.jsx
  src/views/News/index.jsx
  src/views/PeopleSearch/index.tsx
  src/views/PublicProfile/index.jsx
  src/views/Timesheets/index.jsx
  src/views/WellnessCheck/index.jsx
Labels: Code Quality

#1845 Use `date-fns` `formatDistance` instead of custom
  src/components/Profile/components/SchedulePanel/index.jsx
  src/services/utils.ts
Labels: Code Quality

#1823 [Rec-IM] Admin reporting
  src/views/RecIM/views/Admin/Admin.module.scss
  src/views/RecIM/views/Admin/index.jsx
Labels: 5 Points, Rec-IM, S23

#1872 Add patch route to http.ts
  src/services/http.ts
Labels: Bug, Feature

#1883 Recim remove is logo update
  src/services/recim/activity.ts
  src/services/recim/recim.ts
  src/services/recim/sport.ts
  src/services/recim/team.ts
  src/views/RecIM/components/Forms/ActivityForm/index.jsx
  src/views/RecIM/components/Forms/ImageOptions/index.jsx
  src/views/RecIM/components/Forms/SportForm/index.jsx
  src/views/RecIM/components/Forms/TeamForm/index.jsx
Labels: Rec-IM

#1864 S23 CSS Theme Palette Implementation
  src/_vars.scss
  src/app.global.scss
  src/app.module.scss
  src/components/EventList/EventList.module.scss
  src/components/GordonConfetti/index.jsx
  src/components/Header/Header.module.scss
  src/components/Header/components/NavButtonsRightCorner/NavButtonsRightCorner.module.scss
  src/components/Nav/components/NavLinks/index.jsx
  src/components/NavButton/index.jsx
  src/components/Profile/components/Identification/Identification.module.scss
  src/components/Profile/components/Identification/components/SocialMediaLinks/components/LinksDialog/LinksDialog.module.scss
  src/components/Profile/components/Identification/index.jsx
  src/components/Profile/components/MembershipsList/MembershipsList.module.scss
  src/components/Profile/components/OfficeInfoList/OfficeInfoList.module.scss
  src/components/Profile/components/PersonalInfoList/PersonalInfoList.module.scss
  src/components/Profile/components/PersonalInfoList/components/AlumniUpdateForm/components/ContentCard/ContentCard.module.scss
  src/components/Profile/components/VictoryPromise/VictoryPromise.module.scss
  src/components/Providers/index.tsx
  src/components/ThemeModeSwitcher/index.jsx
  src/components/ThemeModeSwitcher/modeSwitcher.module.scss
  src/theme.ts
  src/views/About/About.module.scss
  src/views/About/index.jsx
  src/views/Home/components/CLWCreditsDaysLeft/index.jsx
  src/views/Home/components/DaysLeft/index.jsx
  src/views/Home/components/DiningBalance/index.jsx
  src/views/Home/components/Doughnut.module.scss
  src/views/Home/components/GuestWelcome/GuestWelcome.module.scss
  src/views/Home/components/NewsCard/NewsCard.module.scss
  src/views/Home/components/NewsCard/index.jsx
  src/views/InvolvementsAll/components/Requests/Requests.module.scss
  src/views/InvolvementsAll/index.jsx
Labels: S23, Color/Style

#1822 Add Calendar to Event
  package-lock.json
  package.json
  src/components/EventList/components/EventItem/index.jsx
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.jsx
  src/components/Profile/components/SchedulePanel/components/myScheduleDialog/index.jsx
  src/components/Profile/components/SchedulePanel/index.jsx
Labels: 5 Points, S23

#1893 S23 fix profile advisors
  src/components/Profile/components/PersonalInfoList/index.jsx
  src/services/user.ts
Labels: Bug, Profile Page, 1 Point, Broken Feature, S23

#1817 Guest Transcript
  src/components/Header/components/NavButtonsRightCorner/index.jsx
  src/views/CoCurricularTranscript/guestTranscript.tsx
  src/views/CoCurricularTranscript/index.tsx
Labels: Good First Issue, Feature

#1899 [COLORS] Quick Search and Header conversion
  src/components/Header/Header.module.scss
  src/components/Header/components/QuickSearch/QuickSearch.module.scss
  src/components/Header/components/QuickSearch/index.jsx
  src/theme.ts
Labels: Color/Style

#1874 [COLORS] Changes to theme mode implementation
  src/views/EnrollmentCheckIn/components/CompletedCheckIn/CompletedCheckIn.module.scss
  src/views/EnrollmentCheckIn/components/CompletedCheckIn/index.jsx
  src/views/Events/Events.module.scss
  src/views/Events/index.jsx
  src/views/EventsAttended/index.jsx
  src/views/InvolvementProfile/InvolvementProfile.module.scss
  src/views/InvolvementProfile/components/Membership/components/AdminCard/AdminCard.module.scss
  src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsReceived/index.jsx
  src/views/InvolvementProfile/components/Membership/components/AdminCard/index.jsx
  src/views/InvolvementProfile/components/Membership/components/MemberList/MemberList.module.scss
  src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/MemberListItem.module.scss
  src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.jsx
  src/views/InvolvementProfile/components/Membership/components/MemberList/index.jsx
  src/views/InvolvementProfile/index.jsx
  src/views/InvolvementsAll/components/Requests/components/RequestSent/index.jsx
  src/views/Timesheets/components/SavedShiftsList/SavedShiftsList.module.scss
  src/views/Timesheets/components/SavedShiftsList/index.jsx
  src/views/Timesheets/components/ShiftItem/ShiftItem.module.scss
  src/views/Timesheets/components/ShiftItem/index.jsx
Labels: Color/Style

#1869 [COLORS] Minor Color Theme updates
  src/components/QuickLinksDialog/index.tsx
  src/views/Help/Help.module.scss
  src/views/Help/index.jsx
  src/views/InvolvementsAll/InvolvementsAll.module.scss
  src/views/InvolvementsAll/components/Requests/index.jsx
  src/views/InvolvementsAll/index.jsx
  src/views/PeopleSearch/PeopleSearch.module.scss
  src/views/PeopleSearch/components/PeopleSearchResult/PeopleSearchResult.module.scss
  src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
  src/views/PeopleSearch/components/SearchFieldList/SearchFieldList.module.scss
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
  src/views/Timesheets/index.jsx
Labels: Color/Style

#1926 Fixed cl&w Credits Button Bug
  src/components/EventList/components/EventItem/index.jsx
Labels: Bug

#1866 implementing the dialog box for allowing fac/staff to edit their office location
  src/components/Profile/components/OfficeInfoList/UpdateOfficeLocationDialog/index.jsx
  src/components/Profile/components/OfficeInfoList/index.jsx
  src/services/user.ts
Labels: S23

#1904 implemented searchField selector for the involvements
  src/services/peopleSearch.ts
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: 2 Points, S23

#1918 continue project from MyProfile-Involvments-Clutter - resolved merge conflicts
  src/components/Profile/components/MembershipsList/components/MembershipInfoCard/MembershipInfoCard.module.scss
  src/components/Profile/components/MembershipsList/components/MembershipInfoCard/index.jsx
  src/components/Profile/components/MembershipsList/index.jsx
  src/services/membership.ts
Labels: S23

#1936 changed handleUpdate to clean params when checkboxes are unchecked
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: 1 Point, S23

#1871 implemented the dialog box for changing the fac/staff office hours
  src/components/Profile/components/OfficeInfoList/UpdateOfficeHoursDialog/index.jsx
  src/components/Profile/components/OfficeInfoList/index.jsx
  src/services/user.ts
Labels: S23

#1938 The event info panel closes when you click on the add to calendar button
  src/components/EventList/components/EventItem/index.jsx
Labels: Enhancement, 1 Point, S23

#1939 [COLOR] S23 theme palette implementation
  src/components/BirthdayMessage/BirthdayMessage.module.scss
  src/components/BirthdayMessage/index.jsx
  src/components/GordonOffline/GordonOffline.module.scss
  src/components/GordonOffline/index.jsx
  src/components/Profile/components/Identification/components/SocialMediaLinks/index.jsx
  src/components/Profile/components/PersonalInfoList/components/AlumniUpdateForm/components/ProfileUpdateField/index.jsx
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/UpdatePhone.module.scss
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.jsx
  src/views/ApartmentApp/ApartmentApp.module.scss
  src/views/ApartmentApp/components/StaffMenu/components/ApplicationTable/ApplicationTable.module.scss
  src/views/ApartmentApp/index.jsx
  src/views/News/StudentNews.module.scss
  src/views/News/index.jsx
Labels: Color/Style

#1922 [COLOR] changed color styles to CSS for more files
  src/components/EventList/components/EventItem/EventItem.module.scss
  src/components/OfflineBanner/index.jsx
  src/components/Profile/components/VictoryPromise/components/GraphDisplay.tsx
  src/components/Profile/components/VictoryPromise/components/VictoryPromiseIcons.tsx
  src/services/victoryPromise.ts
  src/theme.ts
  src/views/Admin/components/InvolvementsStatus/index.jsx
  src/views/EnrollmentCheckIn/components/ConfirmCheckIn/index.jsx
  src/views/EnrollmentCheckIn/components/EmergencyContactUpdate/index.jsx
  src/views/EnrollmentCheckIn/components/EnrollmentCheckInWelcome/components/MajorHolds/index.jsx
  src/views/EnrollmentCheckIn/components/EnrollmentCheckInWelcome/index.jsx
  src/views/EnrollmentCheckIn/components/PrivacyAgreement/index.jsx
  src/views/EnrollmentCheckIn/components/RaceEthnicity/index.jsx
  src/views/EnrollmentCheckIn/components/UpdatePhone/index.jsx
  src/views/Events/Events.module.scss
Labels: Color/Style
