Repository gordon-cs/gordon-360-ui, pull requests merged in 2023-09, with the labels that each got.

#2115 Fix styling
  src/_vars.scss
  src/app.jsx
  src/app.module.scss
  src/components/GordonDialogBox/GordonDialogBox.module.scss
  src/components/GordonDialogBox/index.tsx
  src/components/Header/Header.module.scss
  src/components/Header/index.jsx
  src/theme.ts
Labels: Code Quality, Color/Style

#2117 Fix header title in light mode
  src/components/GordonDialogBox/index.tsx
Labels: Color/Style

#2119 Release: JotForm Waiver & Style Fixes
  src/_vars.scss
  src/app.jsx
  src/app.module.scss
  src/components/GordonDialogBox/GordonDialogBox.module.scss
  src/components/GordonDialogBox/index.tsx
  src/components/Header/Header.module.scss
  src/components/Header/index.jsx
  src/theme.ts
  src/views/RecIM/components/Forms/WaiverForm/index.jsx
Labels: Rec-IM
