Repository gordon-cs/gordon-360-ui, pull requests merged in 2024-06, with the labels that each got.

#2269 Add iAttended to Links Page
  src/views/Links/images/iAttended.png
  src/views/Links/index.jsx
Labels: s24

#2271 Make Events Focusable with Tab
  src/components/EventList/components/EventItem/index.jsx
Labels: s24

#2274 Make Enter Key Expand Event
  src/components/EventList/components/EventItem/index.jsx
Labels: s24

#2277 Fix PlanGradYear Link Color and Default Value
  src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/index.jsx
  src/views/PeopleSearch/components/SearchFieldList/components/SearchField/index.tsx
Labels: s24

#2275 [Rec-IM] Add service for participant matches
  src/services/recim/participant.ts
  src/views/RecIM/components/List/index.jsx
  src/views/RecIM/views/Home/index.jsx
Labels: Rec-IM, s24

#2263 Migrate Contexts to TypeScript
  src/contexts/NetworkContext.tsx
Labels: s24

#2264 Migrate hooks to TypeScript
  src/hooks/createUseContext.js
  src/hooks/createUseContext.ts
  src/hooks/index.ts
  src/hooks/useDocumentTitle.ts
  src/hooks/useNetworkStatus.ts
  src/hooks/useUser.ts
  src/hooks/useUserActions.ts
  src/hooks/useWindowSize.ts
Labels: s24

#2282 Restructure msal initialization to hopefully prevent redundant redirects
  src/app.jsx
  src/components/Providers/components/AuthProvider/index.tsx
  src/components/Providers/index.tsx
  src/index.tsx
  src/services/NavigationClient.ts
  src/services/auth.ts
  src/services/authConfig.ts
Labels: Bug, Code Quality

#2283 [Rec-IM] Fix tiny search box
  src/views/RecIM/components/Forms/InviteParticipantForm/index.jsx
Labels: 1 Point, s24

#2276 Make Enter Key Open Course Details & Add Course to Calendar Pop-up
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.tsx
Labels: Accessibility, s24

#2292 collapse membership requests when nothing to do
  src/views/InvolvementsAll/components/Requests/index.jsx
Labels: s24

#2291 Remove period from "By students for students" tagline
  public/images/by_students_for_students.png
Labels: s24

#2296 Make Top Tabs Accessible
  src/components/Header/index.jsx
Labels: s24

#2295 S24 Reduce Startup Console Errors
  src/components/EventList/index.jsx
  src/components/Header/index.jsx
  src/views/Home/components/DiningBalance/index.jsx
Labels: s24

#2288 S24 help page fixes
  package-lock.json
  package.json
  src/views/Help/index.jsx
Labels: s24

#2302 Changed Attended CL&W Link on Events Page
  src/views/Events/index.jsx
Labels: s24

#2298 Schedule visual bugs s24
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/ScheduleCalendar.scss
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.tsx
Labels: 1 Point, s24

#2306 Various Color Fixes
  src/components/Profile/components/PersonalInfoList/index.jsx
  src/views/InvolvementProfile/components/ContactListItem/index.jsx
  src/views/InvolvementProfile/components/Membership/components/MemberList/MemberList.module.scss
  src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.jsx
  src/views/InvolvementProfile/components/Membership/components/MemberList/index.jsx
Labels: s24

#2299 Improve Login/Home Page Accessibility
  src/components/Header/index.jsx
  src/views/Home/components/GuestWelcome/index.jsx
Labels: s24

#2297 S24 Update to REACT 18.x.x
  package.json
  src/components/Profile/components/VictoryPromise/components/GraphDisplay.tsx
  src/index.tsx
  src/views/RecIM/components/RecIMBracket/index.tsx
  src/views/RecIM/views/Home/components/AffiliationsChart/index.jsx
Labels: Patch, s24

#2308 Link Color Fixed Darkmode
  src/components/Profile/components/Identification/Identification.module.scss
  src/theme.ts
Labels: s24

#2309 Fix Disabled Top Tab Contrast
  src/components/Header/Header.module.scss
Labels: s24

#2315 Rename Activities to Involvements
  src/services/involvements.ts
  src/views/Admin/components/InvolvementsStatus/index.jsx
  src/views/InvolvementProfile/components/Membership/components/AdminCard/index.jsx
  src/views/InvolvementProfile/components/Membership/components/NonMemberButtons/index.jsx
  src/views/InvolvementProfile/index.jsx
  src/views/InvolvementsAll/index.jsx
Labels: s24

#2313 Reduce Console Errors
  src/components/EventList/index.jsx
  src/components/Header/index.jsx
  src/components/Nav/components/NavAvatar/index.jsx
Labels: s24

#2312 Add Guest Transcript
  src/components/Header/index.jsx
  src/components/Nav/components/NavLinks/index.jsx
Labels: s24

#2316 Guest Transcript Button for Logged Out Only
  src/components/Nav/components/NavLinks/index.jsx
Labels: s24

#2281 Added Days Left Progress Bar
  package-lock.json
  package.json
  src/views/Home/components/DaysLeft/ProgressBar.module.scss
  src/views/Home/components/DaysLeft/index.jsx
  src/views/Home/index.jsx
Labels: s24

#2317 Switched Birthday Logic from Luxon to Native JS
  src/services/user.ts
Labels: s24

#2328 Reduce Startup Console Errors
  src/components/Nav/components/NavAvatar/index.tsx
Labels: s24

#2330 Fix People Rec-IM Tab Error
  src/components/Nav/components/NavLinks/index.tsx
Labels: 1 Point, s24

#2331 Fix Hamburger Tab Navigation
  src/components/NavButton/index.tsx
Labels: s24

#2311 Dark Mode Color Contrast
  src/theme.ts
  src/views/InvolvementsAll/components/Requests/Requests.module.scss
  src/views/PeopleSearch/components/PeopleSearchResult/PeopleSearchResult.module.scss
Labels: s24

#2333 Fix 2 birthday bugs: day born vs. birthday, and no birthday
  src/services/user.ts
Labels: Bug, 1 Point, s24

#2336 Add Headers to Involvement Profiles
  src/views/InvolvementProfile/index.jsx
Labels: s24
