Repository gordon-cs/gordon-360-ui, pull requests merged in 2024-05, with the labels that each got.

#2219 S24 fixing typos
  src/components/PhotoCropper/index.tsx
  src/views/About/contributors.json
  src/views/IDUploader/index.jsx
Labels: 1 Point, s24

#2220 S24 closing mailbox instructions
  src/components/GordonDialogBox/index.tsx
  src/components/Profile/components/PersonalInfoList/index.jsx
Labels: Bug, 1 Point, s24

#2225 add graduation years for summer practicum 2023
  src/views/About/contributors.json
Labels: s24

#2228 Changed the quick search text color to white.
  src/components/Header/components/QuickSearch/QuickSearch.module.scss
Labels: Bug, Broken Feature, s24

#2246 fix unassigned returning all students
  src/services/peopleSearch.ts
Labels: Bug, 1 Point, s24

#2240 S24 alumni year range
  src/views/PeopleSearch/components/SearchFieldList/components/SearchField/index.tsx
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: 2 Points, s24

#2252 S24 quicklinks improvements
  src/components/Header/index.jsx
  src/components/Nav/components/NavLinks/NavLinks.module.scss
  src/components/Nav/components/NavLinks/index.jsx
  src/components/QuickLinksDialog/QuickLinksDialog.module.scss
  src/components/QuickLinksDialog/index.tsx
  src/routes.jsx
  src/views/Links/images/25-live-logo.jpg
  src/views/Links/images/Canvas.ico
  src/views/Links/images/GoGordonFavicon.ico
  src/views/Links/images/MyGordonFavicon.ico
  src/views/Links/images/criterion.png
  src/views/Links/images/favicon.ico
  src/views/Links/images/fightingscots.svg
  src/views/Links/images/handshake.png
  src/views/Links/images/outlook-icon1.png
  src/views/Links/index.jsx
Labels: s24

#2257 S24 delete chapel credits
  src/hooks/useWatchSystemColorScheme.ts
  src/services/user.ts
  src/views/About/About.module.scss
  src/views/About/index.jsx
  src/views/Home/components/CLWCreditsDaysLeft/index.jsx
  src/views/Home/components/DiningBalance/index.jsx
  src/views/Home/index.jsx
Labels: s24

#2256 Fix non-participants being allowed to make teams post registration close
  src/views/RecIM/views/Activity/index.jsx
Labels: Rec-IM, s24

#2261 Lazy load images when sensible
  src/components/Profile/components/MembershipsList/components/MembershipInfoCard/index.jsx
  src/views/InvolvementsAll/components/InvolvementsGrid/index.jsx
  src/views/News/components/NewsItem/index.jsx
  src/views/PeopleSearch/components/PeopleSearchResult/index.tsx
  src/views/RecIM/components/List/Listing/index.jsx
  src/views/RecIM/views/Home/index.jsx
Labels: Enhancement

#2258 S24 recim match page record
  src/views/RecIM/views/Match/index.jsx
Labels: Rec-IM, s24

#2262 Update styling
  src/views/RecIM/views/Activity/Activity.module.scss
Labels: Rec-IM, s24
