Repository gordon-cs/gordon-360-ui, pull requests merged in 2024-02, with the labels that each got.

#2174 Hl instructionsupdate
  src/views/HousingLottery/studentView/Instructions/index.jsx
Labels: 2 Points

#2184 Show Office Info for Users who Only Have Mail_Location -- CTS Ticket 169936
  src/components/Profile/components/OfficeInfoList/index.jsx
Labels: Bug

#2185 HotFix: CTS Ticket 169936
  src/components/Profile/components/OfficeInfoList/index.jsx
Labels: Bug

#2169 Upgrade dependencies
  .husky/pre-commit
  package-lock.json
  package.json
  src/components/Profile/components/SchedulePanel/components/ScheduleDialog/index.tsx
  src/components/Providers/components/AuthProvider/index.tsx
  src/services/schedule.ts
  src/services/transcript.ts
  src/views/ApartmentApp/components/StudentApplication/index.jsx
  src/views/CoCurricularTranscript/Components/Activity/index.tsx
  src/views/CoCurricularTranscript/Components/Experience/index.tsx
  src/views/RecIM/components/Forms/Form/components/InformationField/index.jsx
  src/views/RecIM/components/List/index.jsx
  src/views/RecIM/views/Admin/index.jsx
  vite.config.ts
Labels: Dependencies
