Repository gordon-cs/gordon-360-ui, pull requests merged in 2024-03, with the labels that each got.

#2191 fix: display building description on my profile
  src/components/Profile/components/OfficeInfoList/index.jsx
Labels: Bug

#2188 Better UI for the React Table
  src/views/HousingLottery/adminView/index.jsx
Labels: 3 Points

#2176 Hl snackbar
  src/views/HousingLottery/adminView/index.jsx
  src/views/HousingLottery/studentView/index.jsx
Labels: 1 Point

#2200 remove the JSON array button and console log, making the column name …
  src/views/HousingLottery/adminView/index.jsx
  src/views/HousingLottery/studentView/Instructions/index.jsx
Labels: 1 Point
