Repository gordon-cs/gordon-360-ui, pull requests merged in 2024-07, with the labels that each got.

#2340 remove material-ui, replaced with @mui
  package-lock.json
  package.json
Labels: Bug, s24

#2332 Fix Header Tab Keyboard Navigation
  src/components/Header/index.tsx
Labels: s24

#2339 Clicking Appearance Button Stays on Current Page
  src/components/Nav/components/NavLinks/index.tsx
Labels: s24

#2343 graph-does-display
  src/components/Profile/components/VictoryPromise/components/GraphDisplay.tsx
Labels: 1 Point, s24

#2334 S24 mailbox information
  src/components/Profile/components/PersonalInfoList/index.jsx
  src/services/user.ts
Labels: s24

#2345 Release: mostly fixes and cleanup
  package-lock.json
  src/components/AppRedirect/index.tsx
  src/components/BirthdayMessage/index.tsx
  src/components/DynamicButton/index.jsx
  src/components/DynamicButton/index.tsx
  src/components/Error/index.tsx
  src/components/ErrorBoundary/index.jsx
  src/components/ErrorBoundary/index.tsx
  src/components/EventList/components/EventItem/index.jsx
  src/components/EventList/components/EventItem/index.tsx
  src/components/EventList/index.tsx
  src/components/GordonConfetti/index.tsx
  src/components/GordonOffline/index.tsx
  src/components/GordonTooltip/index.tsx
  src/components/Header/components/NavAvatarRightCorner/index.tsx
  src/components/Header/components/QuickSearch/index.tsx
  src/components/Header/index.tsx
  src/components/Loader/index.tsx
  src/components/Nav/components/NavAvatar/index.tsx
  src/components/Nav/components/NavLinks/index.tsx
  src/components/Nav/index.tsx
  src/components/NavButton/index.tsx
  src/components/Profile/components/OfficeInfoList/index.jsx
  src/components/Profile/components/PersonalInfoList/PersonalInfoList.module.scss
  src/components/Profile/components/PersonalInfoList/index.jsx
  src/components/Profile/components/SchedulePanel/ScheduleHeader.module.scss
  src/components/Profile/components/SchedulePanel/index.tsx
  src/components/Profile/components/VictoryPromise/components/GraphDisplay.tsx
  src/services/involvements.ts
  src/services/user.ts
  src/theme.ts
  src/views/Admin/components/InvolvementsStatus/index.jsx
  src/views/ApartmentApp/components/StudentApplication/components/BottomBar/index.jsx
  src/views/Home/components/DaysLeft/ProgressBar.module.scss
  src/views/Home/components/DaysLeft/index.jsx
  src/views/Home/index.jsx
  src/views/InvolvementProfile/components/Membership/components/AdminCard/index.jsx
  src/views/InvolvementProfile/components/Membership/components/NonMemberButtons/index.jsx
  src/views/InvolvementProfile/index.jsx
  src/views/InvolvementsAll/components/Requests/Requests.module.scss
  src/views/InvolvementsAll/index.jsx
  src/views/PeopleSearch/components/PeopleSearchResult/PeopleSearchResult.module.scss
Labels: s24

#2338 Paginate Events Page
  src/services/event.ts
  src/views/Events/index.jsx
Labels: 3 Points, s24

#2351 Release: tabbed involvements, time-filtered events, donut-to-pie-chart update (dining balanc)
  src/services/event.ts
  src/views/Events/index.jsx
  src/views/Home/components/DiningBalance/index.jsx
  src/views/InvolvementsAll/index.jsx
Labels: s24

#2349 new-menu-linked-on-dining-balance
  src/views/Home/components/DiningBalance/index.jsx
Labels: 2 Points, s24

#2350 S24 adding practicum names
  src/views/About/contributors.json
Labels: 1 Point, s24

#2348 Add Filter Reminder for Events Page
  src/views/Events/index.jsx
Labels: s24

#2344 Change Past Events Checkbox Color
  src/views/Events/index.jsx
Labels: Color/Style, s24

#2357 s24-add descriptors for links
  src/views/Links/index.jsx
Labels: 1 Point, s24

#2354 HashLinks to Top/Bottom Events Page
  src/views/Events/index.jsx
Labels: s24

#2352 Swap the colors for days remaining
  src/views/Home/components/DiningBalance/index.jsx
Labels: s24

#2358 Give Pencil Icon Buttons Labels for Screen Reader
  src/components/Profile/components/Identification/components/SocialMediaLinks/index.jsx
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.jsx
  src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/index.jsx
Labels: s24

#2353 Return to top of page hashlink-help-page
  src/views/Help/index.jsx
Labels: s24

#2359 Release: small fixes and improvements
  src/components/Profile/components/Identification/components/SocialMediaLinks/index.jsx
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.jsx
  src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/index.jsx
  src/views/About/contributors.json
  src/views/Events/index.jsx
  src/views/Help/index.jsx
  src/views/Home/components/DiningBalance/index.jsx
  src/views/Links/index.jsx
Labels: s24

#2318 S24 migrate components typescript pt2
  src/components/GordonDialogBox/index.tsx
  src/components/GordonOffline/index.tsx
  src/components/GordonTooltip/index.tsx
  src/components/Header/components/QuickSearch/index.tsx
  src/components/PWAInstructions/index.tsx
  src/components/PhotoCropper/index.tsx
  src/components/Profile/components/EmergencyInfoList/index.tsx
  src/components/Profile/components/Identification/components/SocialMediaLinks/components/LinksDialog/index.tsx
  src/components/Profile/components/Identification/components/SocialMediaLinks/index.tsx
  src/components/Profile/components/Identification/index.tsx
  src/components/Profile/components/MembershipsList/components/MembershipInfoCard/index.tsx
  src/components/Profile/components/MembershipsList/index.tsx
  src/components/Profile/components/OfficeInfoList/UpdateMailDestinationDialog/index.tsx
  src/components/Profile/components/OfficeInfoList/UpdateOfficeHoursDialog/index.tsx
  src/components/Profile/components/OfficeInfoList/UpdateOfficeLocationDialog/index.tsx
  src/components/Profile/components/OfficeInfoList/index.tsx
  src/components/Profile/components/PersonalInfoList/components/AlumniUpdateForm/components/ConfirmationHeader/index.tsx
  src/components/Profile/components/PersonalInfoList/components/AlumniUpdateForm/components/ConfirmationRow/index.tsx
  src/components/Profile/components/PersonalInfoList/components/AlumniUpdateForm/components/ContentCard/index.tsx
  src/components/Profile/components/PersonalInfoList/components/AlumniUpdateForm/components/ProfileUpdateField/index.tsx
  src/components/Profile/components/PersonalInfoList/components/AlumniUpdateForm/index.tsx
  src/components/Profile/components/PersonalInfoList/components/UpdatePhoneDialog/index.tsx
  src/components/Profile/components/PersonalInfoList/components/UpdatePlannedGraduationYear/index.tsx
  src/components/Profile/components/PersonalInfoList/index.tsx
  src/components/Profile/components/ProfileInfoListItem/index.tsx
  src/components/Profile/components/SchedulePanel/index.tsx
  src/components/Profile/components/index.tsx
  src/components/Profile/index.tsx
  src/components/Snackbar/index.tsx
  src/components/SpreadsheetUploader/index.tsx
  src/services/membership.ts
  src/services/user.ts
  src/services/utils.ts
  src/views/CoCurricularTranscript/guestTranscript.tsx
Labels: s24

#2362 Accurate Alt Texts for Victory Promise Icons
  src/components/Profile/components/VictoryPromise/components/VictoryPromiseIcons.tsx
Labels: s24
