Repository gordon-cs/gordon-360-ui, pull requests merged in 2024-12, with the labels that each got.

#2445 Admin Landing Page + Admin Actions Checked Action
  src/services/lostAndFound.ts
  src/views/CampusSafety/views/LostAndFoundAdmin/LostAndFoundAdmin.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/MissingItemReportData.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
Labels: LostAndFoundProject24-25

#2450 Fix for Bug on Project Board #97
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
Labels: LostAndFoundProject24-25

#2447 Various Bugfixes
  src/views/CampusSafety/views/LostAndFound/components/DeleteConfirmation/DeleteConfirmation.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
Labels: LostAndFoundProject24-25

#2442 General User UI Visual Improvements
  src/views/CampusSafety/views/LostAndFound/LostAndFound.module.scss
  src/views/CampusSafety/views/LostAndFound/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/MissingItemCreate.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/ReportFound/index.tsx
  src/views/Home/components/LostAndFoundCard/LostAndFoundCard.module.scss
  src/views/Home/components/LostAndFoundCard/index.tsx
  src/views/Home/index.jsx
Labels: LostAndFoundProject24-25

#2444 wmr - Display On Duty Component Info
  src/services/residentLife/RA_OnCall.ts
  src/views/Housing/components/ResidentView/components/OnDuty/index.jsx
  src/views/Housing/index.jsx
Labels: WheresMyRAProject24-25

#2449 Dark Mode Form Label Text Contrast Fix
  src/theme.ts
Labels: Enhancement, Color/Style

#2453 Sticky List Header
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
Labels: LostAndFoundProject24-25

#2459 Color Wrapping Bug Fix
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/MissingItemCreate.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
Labels: LostAndFoundProject24-25

#2460 Lost and Found Testing Environment
  src/components/Header/index.tsx
  src/components/Nav/components/NavLinks/index.tsx
  src/routes.jsx
  src/services/auth.ts
  src/services/lostAndFound.ts
  src/views/CampusSafety/components/Header/Header.module.scss
  src/views/CampusSafety/components/Header/index.tsx
  src/views/CampusSafety/index.tsx
  src/views/CampusSafety/views/LostAndFound/LostAndFound.module.scss
  src/views/CampusSafety/views/LostAndFound/components/DeleteConfirmation/DeleteConfirmation.module.scss
  src/views/CampusSafety/views/LostAndFound/components/DeleteConfirmation/index.tsx
  src/views/CampusSafety/views/LostAndFound/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/MissingItemCreate.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/MissingItemCreate.module.scss.map
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/ConfirmReport.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/reportStolen/ReportStolen.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/reportStolen/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/MissingItemEdit.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/components/confirmReport/ConfirmReport.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/ReportFound/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/LostAndFoundAdmin.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/MissingItemReportData.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/ReportItemPage.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
  src/views/Home/components/LostAndFoundCard/LostAndFoundCard.module.scss
  src/views/Home/components/LostAndFoundCard/index.tsx
  src/views/Home/index.jsx
  src/views/Links/Links.module.scss
  src/views/Links/index.jsx
Labels: LostAndFoundProject24-25

#2457 Board issue82 richie
  src/views/CampusSafety/views/LostAndFound/index.tsx
Labels: LostAndFoundProject24-25

#2454 LostAndFound No Longer Visible in Guest Mode
  src/views/CampusSafety/index.tsx
  src/views/Links/index.jsx
Labels: LostAndFoundProject24-25

#2452 DatePicker and Status Chips on Admin Pages
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
Labels: LostAndFoundProject24-25

#2458 Pickup richie
  src/views/CampusSafety/views/LostAndFound/LostAndFound.module.scss
  src/views/CampusSafety/views/LostAndFound/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/MissingItemEdit.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
  src/views/Home/components/LostAndFoundCard/index.tsx
Labels: LostAndFoundProject24-25

#2464 Fix for Issue with Creating Missing Item Reports in Production
  src/services/lostAndFound.ts
Labels: LostAndFoundProject24-25

#2475 HOTFIX for sticky header padding on admin list Page.
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
Labels: LostAndFoundProject24-25

#2463 Updates for RA/RD views and Auth groups
  .env.development
  src/services/auth.ts
  src/services/residentLife/ResidentStaff.ts
  src/views/Housing/components/RAView/index.jsx
  src/views/Housing/components/RDView/components/MobileView/index.jsx
  src/views/Housing/components/RDView/components/OnDutyTable/index.jsx
  src/views/Housing/index.jsx
Labels: WheresMyRAProject24-25

#2471 WMR - cleaning up ra UI
  src/views/Housing/components/RAView/components/Links/index.jsx
  src/views/Housing/components/RAView/components/Schedule/index.jsx
  src/views/Housing/components/RAView/index.jsx
Labels: WheresMyRAProject24-25

#2451 Default Actions for Missing Item Reports
  src/views/CampusSafety/views/LostAndFound/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
Labels: LostAndFoundProject24-25

#2478 Added Loader to Main L&F Page
  src/views/CampusSafety/views/LostAndFound/index.tsx
Labels: LostAndFoundProject24-25

#2479 Edit action hot fix
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
Labels: LostAndFoundProject24-25

#2465 wmr - Display Hall Mascot Images
  .env.development
  .env.production
  src/views/Housing/Bromley.png
  src/views/Housing/Chase.png
  src/views/Housing/Evans.png
  src/views/Housing/Ferrin.png
  src/views/Housing/Fulton.png
  src/views/Housing/Nyland.png
  src/views/Housing/Tavilla.png
  src/views/Housing/Village.png
  src/views/Housing/Wilson.png
  src/views/Housing/components/ResidentView/components/MyHall/index.jsx
  src/views/Housing/components/ResidentView/components/MyRA/index.jsx
  src/views/Housing/components/ResidentView/components/OnDuty/index.jsx
Labels: WheresMyRAProject24-25

#2480 Added logic for displaying housing tab
  src/components/Header/index.tsx
  src/components/Nav/components/NavLinks/index.tsx
  src/services/auth.ts
  src/services/residentLife/HousingAccess.ts
  src/views/Housing/components/RDView/components/RoomRanges/index.jsx
  src/views/Housing/index.jsx
Labels: WheresMyRAProject24-25

#2484 Removed non MVP code
  src/views/Housing/components/RAView/components/Schedule/index.jsx
  src/views/Housing/components/RAView/components/TaskList/index.jsx
  src/views/Housing/components/RAView/index.jsx
  src/views/Housing/components/RDView/components/RoomRanges/index.jsx
  src/views/Housing/components/RDView/components/UpdateTasks/index.jsx
  src/views/Housing/components/RDView/components/updateTasks/index.jsx
  src/views/Housing/index.jsx
Labels: WheresMyRAProject24-25

#2489 More work for cleaning up MVP
  src/views/Housing/ScottieMascot.png
  src/views/Housing/components/RAView/index.jsx
  src/views/Housing/components/RDView/components/EditDocs/index.jsx
  src/views/Housing/components/RDView/components/OnDutyTable/index.jsx
  src/views/Housing/components/RDView/index.jsx
  src/views/Housing/components/ResidentView/components/HousingWelcome/Banner.jsx
  src/views/Housing/components/ResidentView/index.jsx
Labels: WheresMyRAProject24-25

#2477 Change Admin List to sort by Created Date
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
Labels: LostAndFoundProject24-25

#2491 Update API Route URIs in Service Code
  src/services/lostAndFound.ts
Labels: LostAndFoundProject24-25

#2493 Fix Admin Users Access to Admin UI Pages
  src/services/auth.ts
  src/views/CampusSafety/components/Header/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/index.tsx
Labels: LostAndFoundProject24-25

#2495 Clarified Wording when Creating a Report
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
Labels: LostAndFoundProject24-25

#2496 Luxon to Native Dates
  src/views/CampusSafety/views/LostAndFound/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
Labels: LostAndFoundProject24-25

#2494 New Action Custom Response
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
Labels: LostAndFoundProject24-25

#2497 wmr - Refactoring API routes
  .env.development
  .env.production
  src/components/Header/index.tsx
  src/components/Nav/components/NavLinks/index.tsx
  src/routes.jsx
  src/services/residentLife/HousingAccess.ts
  src/services/residentLife/RA_Checkin.ts
  src/services/residentLife/RA_OnCall.ts
  src/services/residentLife/ResidentStaff.ts
  src/services/residentLife/roomRanges.ts
  src/views/ResLife/Bromley.png
  src/views/ResLife/Chase.png
  src/views/ResLife/Evans.png
  src/views/ResLife/Ferrin.png
  src/views/ResLife/Fulton.png
  src/views/ResLife/Nyland.png
  src/views/ResLife/ScottieMascot.png
  src/views/ResLife/Tavilla.png
  src/views/ResLife/Village.png
  src/views/ResLife/Wilson.png
  src/views/ResLife/components/RAView/components/Links/index.jsx
  src/views/ResLife/components/RAView/index.jsx
  src/views/ResLife/components/RDView/components/EditDocs/index.jsx
  src/views/ResLife/components/RDView/components/MobileView/index.jsx
  src/views/ResLife/components/RDView/components/OnDutyTable/index.jsx
  src/views/ResLife/components/RDView/components/RoomRanges/index.jsx
  src/views/ResLife/components/RDView/index.jsx
  src/views/ResLife/components/ResidentView/components/HousingWelcome/Banner.jsx
  src/views/ResLife/components/ResidentView/components/MyHall/index.jsx
  src/views/ResLife/components/ResidentView/components/MyRA/index.jsx
  src/views/ResLife/components/ResidentView/components/OnDuty/index.jsx
  src/views/ResLife/components/ResidentView/components/Resources/index.jsx
  src/views/ResLife/components/ResidentView/index.jsx
  src/views/ResLife/components/StaffView/index.jsx
  src/views/ResLife/index.jsx
  src/views/ResLife/utils/formatPhoneNumber/formatPhoneNumber.ts
  src/views/ResLife/utils/isMobile/isMobile.ts
  src/views/ResLife/utils/staffType/staffType.ts
Labels: WheresMyRAProject24-25

#2498 Lost and Found UI 1.0 Release
  src/components/Header/index.tsx
  src/components/Nav/components/NavLinks/index.tsx
  src/routes.jsx
  src/services/auth.ts
  src/services/lostAndFound.ts
  src/views/CampusSafety/components/Header/Header.module.scss
  src/views/CampusSafety/components/Header/index.tsx
  src/views/CampusSafety/index.tsx
  src/views/CampusSafety/views/LostAndFound/LostAndFound.module.scss
  src/views/CampusSafety/views/LostAndFound/components/DeleteConfirmation/DeleteConfirmation.module.scss
  src/views/CampusSafety/views/LostAndFound/components/DeleteConfirmation/index.tsx
  src/views/CampusSafety/views/LostAndFound/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/MissingItemCreate.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/MissingItemCreate.module.scss.map
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/ConfirmReport.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/reportStolen/ReportStolen.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/reportStolen/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/MissingItemEdit.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/components/confirmReport/ConfirmReport.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/ReportFound/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/LostAndFoundAdmin.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/MissingItemReportData.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/ReportItemPage.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
  src/views/Home/components/LostAndFoundCard/LostAndFoundCard.module.scss
  src/views/Home/components/LostAndFoundCard/components/ActiveReports/index.tsx
  src/views/Home/components/LostAndFoundCard/components/FoundReports/index.tsx
  src/views/Home/components/LostAndFoundCard/index.tsx
  src/views/Home/index.jsx
  src/views/Links/Links.module.scss
  src/views/Links/index.jsx
Labels: Release, LostAndFoundProject24-25

#2504 Where's my RA Release
  .env.development
  package-lock.json
  src/components/Header/index.tsx
  src/components/Nav/components/NavLinks/index.tsx
  src/routes.jsx
  src/services/auth.ts
  src/services/residentLife/HousingAccess.ts
  src/services/residentLife/RA_Checkin.ts
  src/services/residentLife/RA_OnCall.ts
  src/services/residentLife/ResidentStaff.ts
  src/services/residentLife/roomRanges.ts
  src/views/ResLife/Bromley.png
  src/views/ResLife/Chase.png
  src/views/ResLife/Evans.png
  src/views/ResLife/Ferrin.png
  src/views/ResLife/Fulton.png
  src/views/ResLife/Nyland.png
  src/views/ResLife/ScottieMascot.png
  src/views/ResLife/Tavilla.png
  src/views/ResLife/Village.png
  src/views/ResLife/Wilson.png
  src/views/ResLife/components/RAView/components/Links/index.jsx
  src/views/ResLife/components/RAView/index.jsx
  src/views/ResLife/components/RDView/components/EditDocs/index.jsx
  src/views/ResLife/components/RDView/components/MobileView/index.jsx
  src/views/ResLife/components/RDView/components/OnDutyTable/index.jsx
  src/views/ResLife/components/RDView/components/RoomRanges/index.jsx
  src/views/ResLife/components/RDView/index.jsx
  src/views/ResLife/components/ResidentView/components/HousingWelcome/Banner.jsx
  src/views/ResLife/components/ResidentView/components/MyHall/index.jsx
  src/views/ResLife/components/ResidentView/components/MyRA/index.jsx
  src/views/ResLife/components/ResidentView/components/OnDuty/index.jsx
  src/views/ResLife/components/ResidentView/components/Resources/index.jsx
  src/views/ResLife/components/ResidentView/index.jsx
  src/views/ResLife/components/StaffView/index.jsx
  src/views/ResLife/index.jsx
  src/views/ResLife/utils/formatPhoneNumber/formatPhoneNumber.ts
  src/views/ResLife/utils/staffType/staffType.ts
Labels: WheresMyRAProject24-25
