Repository gordon-cs/gordon-360-ui, pull requests merged in 2025-06, with the labels that each got.

#2683 Add name change request button
  src/components/Profile/components/Identification/index.tsx
Labels: Enhancement, Modification, 2 Points, s25

#2685 S25 join date
  src/components/Profile/components/PersonalInfoList/index.tsx
  src/services/user.ts
  src/views/CoCurricularTranscript/guestTranscript.tsx
Labels: s25

#2670 S25 graduation flag
  src/components/Profile/components/PersonalInfoList/index.tsx
  src/components/Profile/index.tsx
  src/components/Snackbar/index.tsx
  src/services/user.ts
Labels: s25

#2684 Re-label alumni information update button and fac/staff update instructions
  src/components/Profile/components/PersonalInfoList/index.tsx
Labels: s25

#2654 involvement cards fit for any size window
  src/views/InvolvementsAll/components/InvolvementsGrid/index.jsx
Labels: s25

#2661 fixing warnings for spacing and favor of lower_case
  public/sw.js
  public/sw_guest_cache.js
  public/sw_user_cache.js
  src/components/GordonOffline/index.tsx
  src/components/Header/index.tsx
  src/components/NavButton/index.tsx
  src/components/PWAInstructions/index.tsx
  src/components/PaletteSwitcherDialog/index.tsx
  src/components/Profile/components/Identification/index.tsx
  src/components/Profile/components/MembershipsList/index.tsx
  src/components/Profile/components/OfficeInfoList/UpdateMailDestinationDialog/index.tsx
  src/components/Profile/components/OfficeInfoList/index.tsx
  src/hooks/createUseContext.ts
  src/hooks/useDocumentTitle.ts
  src/hooks/useNetworkStatus.ts
  src/services/analytics.ts
  src/services/error.ts
  src/services/event.ts
  src/services/housing.ts
  src/services/http.ts
  src/services/involvements.ts
  src/services/lostAndFound.ts
  src/services/news.ts
  src/services/session.ts
  src/services/storage.ts
  src/services/transcript.ts
  src/services/utils.ts
  src/views/CoCurricularTranscript/Components/Activity/index.tsx
  src/views/PeopleSearch/components/SearchFieldList/index.tsx
Labels: 1 Point, s25

#2663 RecIM admin activities filter sorted by status, name, and start date
  src/views/RecIM/views/Admin/index.jsx
Labels: s25
