Repository gordon-cs/gordon-360-ui, pull requests merged in 2025-02, with the labels that each got.

#2546 Lazy Loading for Missing Item Reports
  src/services/lostAndFound.ts
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
Labels: LostAndFoundProject24-25

#2547 Added RAs on call to RA view
  .env.development
  src/views/ResLife/components/RAView/index.jsx
  src/views/ResLife/index.jsx
Labels: WheresMyRAProject24-25

#2549 Fixes from UI Review
  src/services/http.ts
  src/services/lostAndFound.ts
  src/views/CampusSafety/components/Header/index.tsx
  src/views/CampusSafety/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
Labels: LostAndFoundProject24-25

#2548 Lost and Found Release 1.1
  src/services/http.ts
  src/services/lostAndFound.ts
  src/views/CampusSafety/components/Header/index.tsx
  src/views/CampusSafety/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/ConfirmReport.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/components/reportStolen/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/components/confirmReport/ConfirmReport.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/components/confirmReport/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
  src/views/Home/components/LostAndFoundCard/LostAndFoundCard.module.scss
  src/views/Home/components/LostAndFoundCard/components/ActiveReports/index.tsx
  src/views/Home/components/LostAndFoundCard/index.tsx
Labels: Release, LostAndFoundProject24-25

#2551 Remove luxon
  package-lock.json
  package.json
  src/components/Profile/components/SchedulePanel/components/ScheduleCalendar/index.tsx
  src/services/event.ts
  src/services/news.ts
  src/views/ApartmentApp/components/StaffMenu/index.jsx
  src/views/ApartmentApp/components/StudentApplication/components/ApplicationDataTable/index.jsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
Labels: Dependencies

#2558 Found Item Create Fixes
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemFormCreate.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/index.tsx
Labels: LostAndFoundProject24-25

#2555 Added RA option to check in to additional halls
  .env.development
  src/services/residentLife/RA_Checkin.ts
  src/views/ResLife/components/RAView/index.jsx
Labels: WheresMyRAProject24-25

#2559 Code Reuse
  src/views/CampusSafety/components/CustomDatePicker/index.tsx
  src/views/CampusSafety/components/GordonPersonAutocomplete/index.tsx
  src/views/CampusSafety/components/Helpers/index.ts
  src/views/CampusSafety/components/StatusChip/StatusChip.module.scss
  src/views/CampusSafety/components/StatusChip/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsEdit/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsList/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
Labels: LostAndFoundProject24-25

#2560 Missing Item Create and Edit Reusable Component
  src/views/CampusSafety/components/ItemForm/ItemForm.module.scss
  src/views/CampusSafety/components/ItemForm/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/MissingItemCreate.module.scss
  src/views/CampusSafety/views/LostAndFound/views/MissingItemCreate/index.tsx
  src/views/CampusSafety/views/LostAndFound/views/MissingItemEdit/index.tsx
Labels: LostAndFoundProject24-25

#2552 Found item entry richie
  src/components/Header/index.tsx
  src/services/lostAndFound.ts
  src/views/CampusSafety/components/Constants/index.ts
  src/views/CampusSafety/components/CustomDatePicker/index.tsx
  src/views/CampusSafety/components/GordonPersonAutocomplete/index.tsx
  src/views/CampusSafety/components/Helpers/index.ts
  src/views/CampusSafety/components/StatusChip/StatusChip.module.scss
  src/views/CampusSafety/components/StatusChip/index.tsx
  src/views/CampusSafety/index.tsx
  src/views/CampusSafety/views/LostAndFound/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemFormCreate.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsEdit/FoundItemFormEdit.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsEdit/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsList/FoundItemList.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/FoundItemsList/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/FoundItems/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/MissingItemList.module.scss
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/MissingItemReportData/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/components/ReportItemPageOther/index.tsx
  src/views/CampusSafety/views/LostAndFoundAdmin/views/MissingItemList/index.tsx
  src/views/Home/components/LostAndFoundCard/components/ActiveReports/index.tsx
  src/views/Home/components/LostAndFoundCard/components/FoundReports/index.tsx
Labels: LostAndFoundProject24-25

#2531 RA TaskList
  src/services/residentLife/Tasks.ts
  src/views/ResLife/components/RAView/components/TaskList/index.jsx
  src/views/ResLife/components/RAView/index.jsx
Labels: WheresMyRAProject24-25

#2567 Updated Basic Select Name
  src/views/ResLife/components/RAView/index.jsx
  src/views/ResLife/components/RDView/components/OnDutyMobileView/index.jsx
  src/views/ResLife/components/RDView/components/TaskList/index.jsx
  src/views/ResLife/components/RDView/index.jsx
  src/views/ResLife/components/StaffView/index.jsx
Labels: WheresMyRAProject24-25

#2566 Remove Under Construction Text
  src/views/LostAndFound/views/Admin/index.tsx
Labels: LostAndFoundProject24-25

#2571 Wmr checkin refactoring
  src/views/ResLife/components/RAView/components/CheckIn/index.jsx
  src/views/ResLife/components/RAView/index.jsx
Labels: WheresMyRAProject24-25
